services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80


    
volumes:
  redis-data:
  postgres-data: